In [2]:
import numpy as np

In [3]:
A = np.random.rand(3,2)
B = np.sum(A, axis=0, keepdims=True)
B

array([[1.62254986, 1.31457501]])

In [4]:
import math
import numpy as np
def sigmoid(x):
    return np.exp(x)

In [5]:
vectors = [[[1,2,3],[1,3,5]], [[4,5,6],[3,5,6]], [[7,8,9],[1,2,3]]]
np_vectors = np.array(vectors)
print(sigmoid(np_vectors))


[[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
  [2.71828183e+00 2.00855369e+01 1.48413159e+02]]

 [[5.45981500e+01 1.48413159e+02 4.03428793e+02]
  [2.00855369e+01 1.48413159e+02 4.03428793e+02]]

 [[1.09663316e+03 2.98095799e+03 8.10308393e+03]
  [2.71828183e+00 7.38905610e+00 2.00855369e+01]]]


In [6]:
atq  = np.random.rand()
print(atq)

0.955758927053696


In [7]:
print(np_vectors.shape)

(3, 2, 3)


In [8]:
print(np.exp(np_vectors))
print(np.sum(np.exp(np_vectors), axis=1, keepdims=True))

[[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
  [2.71828183e+00 2.00855369e+01 1.48413159e+02]]

 [[5.45981500e+01 1.48413159e+02 4.03428793e+02]
  [2.00855369e+01 1.48413159e+02 4.03428793e+02]]

 [[1.09663316e+03 2.98095799e+03 8.10308393e+03]
  [2.71828183e+00 7.38905610e+00 2.00855369e+01]]]
[[[5.43656366e+00 2.74745930e+01 1.68498696e+02]]

 [[7.46836870e+01 2.96826318e+02 8.06857587e+02]]

 [[1.09935144e+03 2.98834704e+03 8.12316946e+03]]]


In [9]:
z = [3,4]
print(np.square(z))

[ 9 16]


In [10]:
abc  = np.zeros((2,3))
abc

array([[0., 0., 0.],
       [0., 0., 0.]])

In [11]:
if (4 != 5):
    print("4 is not equal to 5")
else:
    print("4 is equal to 5")

4 is not equal to 5


In [12]:
x = np.array([
    [[1, 2, 4], [2, 3, 5], [2, 3, 5]],
    [[3, 4, 5], [4, 5, 5], [2,3,5]],
    [[6, 7, 1], [7, 8, 1], [2,9,5]]
    ])
count = 0
for i in range(0,len(x)):
    for j in range(0,len(x[i])):
        for k in range(0,len(x[j])):
            count += 1
            if x[i][j][k] == 9:
                print("Found 9 at position:", (i, j, k))
print("Total count:", count)

Found 9 at position: (2, 2, 1)
Total count: 27


# CNN

In [14]:
boxes = np.array([
    [0.5, 0.5, 1.0, 1.0],   # Box 1: x, y, w, h
    [0.2, 0.3, 0.4, 0.5]    # Box 2: x, y, w, h
])

box_confidence = np.array([
    [0.9],  # Box 1: 90% confident there's an object
    [0.3]   # Box 2: 30% confident there's an object
])

box_class_probs = np.array([
    [0.05, 0.9, 0.05],  # Box 1: probabilities for [cat, dog, car]
    [0.6, 0.2, 0.2]     # Box 2: probabilities for [cat, dog, car]
])
print(box_confidence.shape)
print(box_class_probs.shape)
print(box_confidence * box_class_probs)

(2, 1)
(2, 3)
[[0.045 0.81  0.045]
 [0.18  0.06  0.06 ]]
